# Generated by Django 5.0.1 on 2024-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='internshipapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojt_duration', models.IntegerField()),
                ('province', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('school_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'internshipapplication',
            },
        ),
    ]
