# Generated by Django 5.0.1 on 2024-02-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilcdbcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internshipapplication',
            table='InternshipApplication',
        ),
    ]
